name: "Compile ComputerCraft scripts"

# Compiles scripts and pushes to build branch for use in game

on:
  push:
    branches: [ main ]
jobs:
  build-scripts:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@main
      - uses: leafo/gh-actions-lua@master
      - uses: leafo/gh-actions-luarocks@master

      - name: Install Fennel
        run: luarocks install fennel

      - name: Compile
        run: make

      - name: Remove files except build directory
        run: |
          shopt -s extglob
          rm -rf !("build")

      - name: Move build to root
        run: mv build/* .

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Update files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: build
          force: true
